### ISSUE TITLE
special characters not export .strm 

### ISSUE THREAD

**Issue by lovestonelay** [cguZZman/plugin.googledrive#317]
special characters like as "|" ":"  can not export 
please how to fix the problem sir

**Comment by luhanmcs** [comment]
This is a limitation of operating systems file names, not the addon, windows® for example does not allow these characters in any file. Sample Portuguese-BR language, with translation:


"file names cannot contain any of the following characters: \/:*?"<>|"
![image](https://user-images.githubusercontent.com/22850716/215393339-2be84618-1960-4685-9126-36277910f6ae.png)

Obs.. In google drive it allows these characters, but it is highly recommended not to use them, due to incompatibilities in some OS.
