### ISSUE TITLE
Error 403 in logs, files do not play

### ISSUE THREAD

**Issue by Pixstrad** [cguZZman/plugin.googledrive#35]
**Describe the bug**
Error 403 in logs when trying to play a file located on Google Drive

**To Reproduce**
1. Add account via addon
2. Add network source
3. Wait for library scan to finish
4. Attempt to play a file
5. "One or more items failed to play..." error in Kodi
6. Check log file, see errors below

**Your debug log file** https://pastebin.com/XgD9bMXy

--

I have completely removed (including AppData & settings folders) and reinstalled Kodi, and this issue still persists.

**Comment by cguZZman** [comment]
Looks like you didn't turn on the debug mode in Kodi to reproduce the issue. Your log doesn't include debug messages.
Anyway, a 403 error is a ban from google. This is probably because you are sharing your account. Which in that case there is nothing else to do from the addon side.
Try playing the video from with the addon navigation using the "transcoding" option. That option doesn't download the video from the google api.

**Comment by Pixstrad** [comment]
I actually have never shared my account, so it's very strange I would get banned. I will attempt the transcoding option and fully understand that this is out of your hands otherwise. Thank you for getting back to me!
