### ISSUE TITLE
Stream doesn't work unless asked for stream format 

### ISSUE THREAD

**Issue by PedroC1999** [cguZZman/plugin.googledrive#53]
I am attempted to stream files from my Google Drive, however I can only get them to open if I select the "always ask for the stream format to play" and select "1080p" (which is the resolution of my monitor"

If I select Original, the loading circle appears but nothing happens, then it dissapears. 

Possible workaround/solution: have an option to set the default format, as opposed to the popup appearing every time. 

I have attached logs 

https://paste.kodi.tv/ipiniyeveg

**Comment by VsnGamer** [comment]
I have a similar problem
Since Kodi 18.1 the plugin seems to pull data from Google Drive very slowly
For example, if i try to watch a low bitrate video it plays fine, but for a high bitrate video, it cannot keep up.
Stream format works because it compresses the video to a low bitrate(but bad quality)
Kodi(or google) probably changed something in the way plugins pull data so plugin needs a quick(hopefully) fix.

**Comment by PedroC1999** [comment]
I would like to add I am using the latest LibreElec on an x86 computer

**Comment by VsnGamer** [comment]
This makes the plugin almost unusable because you can't watch with the best quality and ask for stream doesn't work when using google drive as a source.

**Comment by gsantosoliver** [comment]
> I have a similar problem
> 
> Since Kodi 18.1 the plugin seems to pull data from Google Drive very slowly
> 
> For example, if i try to watch a low bitrate video it plays fine, but for a high bitrate video, it cannot keep up.
> 
> Stream format works because it compresses the video to a low bitrate(but bad quality)
> 
> Kodi(or google) probably changed something in the way plugins pull data so plugin needs a quick(hopefully) fix.

have you tried this in the earlier version of Kodi? Was it working ok? If so I will try to install the older version until this is fixed. Thanks.

**Comment by gsantosoliver** [comment]
> I have a similar problem
> 
> Since Kodi 18.1 the plugin seems to pull data from Google Drive very slowly
> 
> For example, if i try to watch a low bitrate video it plays fine, but for a high bitrate video, it cannot keep up.
> 
> Stream format works because it compresses the video to a low bitrate(but bad quality)
> 
> Kodi(or google) probably changed something in the way plugins pull data so plugin needs a quick(hopefully) fix.

@VsnGamer - have you tried this in the earlier version of Kodi? Was it working ok? If so I will try to install the older version until this is fixed. Thanks.

**Comment by gorman42** [comment]
Is this specific to Kodi 18.1 or was the problem present with 18.0 too?

**Comment by VsnGamer** [comment]
I'm testing right now on my PC with kodi 17.6 and the problem does not occur, it loads fast like it should.

I will update to 18.0 and test.

**Comment by PedroC1999** [comment]
This happens on my 18.0 based LibreElec and Windows Kodi based systems

**Comment by gsantosoliver** [comment]
@gorman42 @VsnGamer @PedroC1999 - I am using 18.1 on both Shield TV and Smartphone OnePlus 6  - the issue does not happen on the phone! Here is a detailed explanation of the problem I am facing -  #54

**Comment by VsnGamer** [comment]
I tested Kodi 17.6, 18.0, 18.1 on PC and none had problems

My android TV box still has the problem, it seems to occur only on some devices..

**Comment by VsnGamer** [comment]
This and #54 are basically the same, maybe change title of this one

**Comment by cguZZman** [comment]
The original issue has nothing to do with #54.
The stream doesn't play for @PedroC1999 because a ban on him from google accordingly with his debug log file. If you have a similar issue, post your debug log file. We don't have to be guessing the reason. 
If you see a "HTTP returned error 403" in your debug log file, then it's a ban.
Google is prone to ban users with multiple requests to its APIs or multiple play on a single file thru the API. The playing of a video file directly in Google Drive page is done thru the stream format url also, that's why it always works there and that's why this option in the addon solves the problem.

The slow source error is a problem with your internet connection or a problem with your device. All the addon does is to get the correct URL from google and pass it to kodi to be played. Kodi then plays it directly from google's servers. The addon can do nothing to fix your internet speed or kodi device.

I'm closing this issue since is out of the scope of the addon.

**Comment by VsnGamer** [comment]
Weird because I also have 200mbps on the android tv

**Comment by PedroC1999** [comment]
I politely disagree with you. Although I believe I may have gotten rate limited during the loading of the library, the issue whereby the stream fails in original quality, but always works in 1080p, is addon dependant. It used to work in versions prior to 18.x

**Comment by cguZZman** [comment]
So your disagreement is about the reason your file is not being played? No need to be agreed on this. Just go to your debug log file and check the error after the google video is tried to be played by kodi, then you can research about that error.
And I already explained why it works in 1080p or any other format played thru the stream format option. Your error is a know issue with all kind of programs using google apis.
