### ISSUE TITLE
Library update does not remove non-existent content

### ISSUE THREAD

**Issue by jmiskinis** [cguZZman/plugin.googledrive#59]
**Describe the bug**
Library update does not automatically remove content which is no longer available on Google Drive.

**To Reproduce**
1. Go to Google Drive, remove a video file which was previously added to Kodi's library.
2. Open Kodi and update the library.
3. Non-existent entries are not automatically removed from the library,

**Comment by cguZZman** [comment]
Library update is intended to add new titles only, not to remove them. This is the way Kodi works. Not an addon function at all. 
It make sense, actually, after you read the comments about why it was developed this way. Check the comments of the kodi team members here: https://forum.kodi.tv/showthread.php?tid=68326

There is a way to override this, though. It's stated in the post mentioned before. You need to modify your advancedsettings.xml file and set the cleanonupdate to true.
https://kodi.wiki/?title=Advancedsettings.xml#.3Cvideolibrary.3E

I'm going to close this issue since it's not valid.

**Comment by jmiskinis** [comment]
Thank you for a comprehensive reply.
