### ISSUE TITLE
Movies do not play anymore

### ISSUE THREAD

**Issue by gsantosoliver** [cguZZman/plugin.googledrive#64]
**Describe the bug**
The movies I have in Google Drive do not play anymore. They kind of start and then stops without showing the screen. It is important to mention it was working fine until today. This problem started today.

**To Reproduce**
1. Have a google drive account with movies on it, Kodi and the add-on properly installed and setup
2. Navigate to any movie using the add-on and play it (in my case, "A Star is Born")
3. The little play icon and info quickly appears in the top right side of the window and then it vanishes - the movie does not even start.

**Your debug log file**
Here is the log file: https://paste.kodi.tv/lapukobuju.kodi

**Comment by gorman42** [comment]
As I replied to you on Kodi forums, you have an error 403 in your log.
Google is refusing access to the file because download quota has been exceeded.
It usually resets in 24 hours.
There's nothing the plugin can do about that.

**Comment by gsantosoliver** [comment]
> As I replied to you on Kodi forums, you have an error 403 in your log.
> Google is refusing access to the file because download quota has been exceeded.
> It usually resets in 24 hours.
> There's nothing the plugin can do about that.

mmm, how do I confirm that? What is the download quota? I have gone to several places in Google using the account I am using in the add-on (which is different from the account that owns the content) and have not found any download quota. Could you please tell me where it is?

**Comment by gorman42** [comment]
The download quota concerns the account that owns the content. You are not going to find the download quota anywhere, unfortunately. I know because I've been looking for it for months. The most frequent reference speaks about an overall 10TB daily download quota for an account. But admin console proves that a single movie being watched generates four download events and, as far as I've been able to get from Google customer service, every event counts for the full size of the file.

Now, I have no mean of telling the size of your file. But if that account is sharing many movies, of several GBs each... and some of them are accessed through Google Drive File Stream (that generates hundreds of download event per movie watched, due to differences in how data is accessed)... well, you do the math.

**Comment by gorman42** [comment]
In any case, if you have the download link for the file. Or it's shared with you. You can try accessing it from Drive's web interface. Try downloading it. If it tells you "the download quota for this file has been exceeded", that's what I'm referring to.

**Comment by gsantosoliver** [comment]
@gorman42 - lets suppose this is the case. Does the download info (not while playing, think of it as the export strm of listing files through the plugin does) count as well? If so, I see one place where the the plugin could be reviewed as trying to reduce the number of api requests maybe? 

The test you have just asked me to do: shall I do this with the owner account or the account I am using to play the movie? 

Thank you for the help!

**Comment by gorman42** [comment]
Nope, the creation of .strm files does not generate download events. It's a listing call from the API (simply guessing here).
It's the same. No account should be able to download for 24 hours. Not only that file but all files owned by the account that owned the file generating the 404 message. This in my direct experience, at least.

**Comment by gsantosoliver** [comment]
> Nope, the creation of .strm files does not generate download events. It's a listing call from the API (simply guessing here).
> It's the same. No account should be able to download for 24 hours. Not only that file but all files owned by the account that owned the file generating the 404 message. This in my direct experience, at least.

Oh crap, that is really bad! I am not able to download anything! WOW! I just wonder if there is a place in the google admin console where I can track the quota usage!

**Comment by cguZZman** [comment]
The download quota does not appear in any console. Do the test @gorman42 asked you to do and if you can play your videos in the Google Drive page directly, you could play them with the addon with the stream format option. That option is using the same link a the page. 
This option is not available when you are using your drive as a source though. Only with strm files or directly within the addon navigation.

I'm closing this issue since is out of the scope of the addon.

**Comment by gsantosoliver** [comment]
@cguZZman - thanks for answering
Ok, so tell me more about this "stream format"- I am using the .strm file so:
1. What does it do?
2. Does it avoid this quota issue?

**Comment by gorman42** [comment]
@gsantosoliver if you are not able do download anything, then it means that the account has been blocked for 24 hours. If you are using .strm files, it means that probably there were many downloads from the same source. I don't see any other reasonable explanation.

The complete remux of the movie you were playing (I don't know if it was a remux or something somebody re-encoded, remux is worst case scenario, for size) weighs in at about 45GB. With .strm you play that generating 4 download events (I think it's because of simultaneous sessions to optimize the connection, downloading from the web Drive interface generates a single download event).
So... it would count for 180GB. To reach 10TB you would need to watch the movie 55 times (impossible in one day for a single user).

Problem might come if multiple users, many users are playing back from the same account's content **and/or** if some of the other people playing back content from that account are accessing it through Google Drive File Stream (which generates hundreds of download events for a single video file).

**Comment by gorman42** [comment]
The "stream format" Carlos was referring to is the one you access through Add-on settings.

"Always ask for the stream format before play" activated means you can opt to play back transcoded videos from Drive. It's the same as selecting resolution in YouTube (same tech). But I don't think 4K option is available among the choices available. Plus, if the file has multiple audio track (think main track plus commentary) the wrong track might get selected and you don't have a way to switch (unless I'm mistaken).

**Comment by gsantosoliver** [comment]
> @gsantosoliver if you are not able do download anything, then it means that the account has been blocked for 24 hours. If you are using .strm files, it means that probably there were many downloads from the same source. I don't see any other reasonable explanation.
> 
> The complete remux of the movie you were playing (I don't know if it was a remux or something somebody re-encoded, remux is worst case scenario, for size) weighs in at about 45GB. With .strm you play that generating 4 download events (I think it's because of simultaneous sessions to optimize the connection, downloading from the web Drive interface generates a single download event).
> So... it would count for 180GB. To reach 10TB you would need to watch the movie 55 times (impossible in one day for a single user).
> 
> Problem might come if multiple users, many users are playing back from the same account's content **and/or** if some of the other people playing back content from that account are accessing it through Google Drive File Stream (which generates hundreds of download events for a single video file).

Thank you for the detailed explanation on how things work behind the scenes. I understand that 4 would be nice for a slow connection, but maybe it would be a waste of download quota for people who have really fast internet connection, so here is the question: is there a way to set the download events from 4 to a lower number (lets say 2) or let the user select that option?

Thank you for the explanation on the stream as well.

**Comment by gorman42** [comment]
I'm not the developer, so I'm not sure if what you ask could be doable.

What I can point out to @cguZZman is this application: https://github.com/moisesmcardona/GoogleDriveUploadTool

Contrary to its name, the application allows for downloading of files, not just uploading. And I've just used it to download a 6.5GB file with a **single** download event being generated.
If I access the same movie through Google Drive plugin, as soon as playback starts **four** download events are generated.

**Comment by gsantosoliver** [comment]
> Edit: I'll actually open a new issue on this, as this being closed I'm not sure if it's read anymore.

It sounds good. Please add me as a subscriber on that new issue. Thank you!

**Comment by cguZZman** [comment]
There is something fundamental about the interaction of any addon and Kodi that is important to mention, and I think I already mentioned it before: when playing a video, the role of an addon is to get the real URL of a video and then pass it to Kodi. In this case the role of this addon is to get the real URL from google servers and then kodi will play the video. This means there is no download from the addon side. Kodi is in charge of downloading the file.
How Kodi downloads the video so it can be played and how many times it's totally up to Kodi. But for the sake of providing more information, I already debugged how kodi interacts with URLs some years ago. And yes, it makes multiples request of the file before playing. I believe this is to get the header data from the video and some other stuff. It's not downloading the complete file though.
So from my point of view, there is no much the addon can do.

**Comment by gsantosoliver** [comment]
@cguZZman - it makes sense. Thank you for the explanation.
