### ISSUE TITLE
Watching a movie generating a single download event instead of four.

### ISSUE THREAD

**Issue by gorman42** [cguZZman/plugin.googledrive#66]
**Is your feature request related to a problem? Please describe.**
Since, apparently, Drive daily download limits are impacted by every download event that is generated (viewable under Admin console/Reports/Audit/Drive), i.e. every download event generated counts as the full size of the file being accessed, it would be nice if accessing a single movie/tv episode could generate a single download event instead of the four that are currently generated by the plugin.
This "download events count as a full size download each" has been confirmed to me by second tier Drive customer service.

**Describe the solution you'd like**

Not a solution, per se, but [this application](https://github.com/moisesmcardona/GoogleDriveUploadTool), contrary to its name, allows for downloading of files, not just uploading. And I've just used it to download a 6.5GB movie with a single download event being generated.
If I access the same movie through Google Drive plugin, as soon as playback starts four download events are generated.

**Comment by gsantosoliver** [comment]
@gorman42 @cguZZman - I think this is related to this ticket. I played about 15 seconds of this movie and then I went to the Google Suite admin/Audit tool - here is what I see:
![Screen Shot 2019-03-19 at 2 23 41 PM](https://user-images.githubusercontent.com/31668431/54627860-051c6a00-4a53-11e9-8ab3-8eb683da21a7.png)

Unfortunately in the audit is not described how much data for each download entry has been used from the daily quota. Would you guys know if Google counts only the amount of data actually downloaded or the entire file size in each one of those entries?

**Comment by cguZZman** [comment]
Ok, I'll copy paste my response from the previous related issue:

There is something fundamental about the interaction of any addon and Kodi that is important to mention, and I think I already mentioned it before: when playing a video, the role of an addon is to get the real URL of a video and then pass it to Kodi. In this case the role of this addon is to get the real URL from google servers and then kodi will play the video. This means there is no download from the addon side. Kodi is in charge of downloading the file.
How Kodi downloads the video so it can be played and how many times it's totally up to Kodi. But for the sake of providing more information, I already debugged how kodi interacts with URLs some years ago. And yes, it makes multiples request of the file before playing. I believe this is to get the header data from the video and some other stuff. It's not downloading the complete file though.
So from my point of view, there is not much the addon can do. 

I think you could open an issue for Kodi. May be they could do something different that could be more efficient when playing a video from a URL, and not treat the URL as local file where you can open/seek/read a file as pleased without impact.

I'm closing this issue since is out of the scope of the addon.

**Comment by gorman42** [comment]
Thanks Carlos, it all makes sense. One would hope that the "events" don't count as full downloads but, unfortunately, Google tier 2 Drive support told me the opposite. That is: every download event counts as a full download.
I would downplay that, were it not for my account getting locked up for 24 hours after watching 52 minutes of a movie that generated over 200 download events.
