### ISSUE TITLE
No files shown

### ISSUE THREAD

**Issue by Big-Daddy80** [cguZZman/plugin.googledrive#70]
Won't show any files ( photos, pdf, etc. ), except zip files.

Runs on kodi on a pi B+.

**To Reproduce**
Installed newest  version from rep and logged in succesfully. Opened my drive and browsed some folders, which are indeed shown correctly and completely.

Any advice?

**Comment by cguZZman** [comment]
Sounds like you were accessing your drive thru the Videos option where only video files will be displayed. If you want your photos to show, you need to access your drive thru the Photos menu.
Other type of files will not be displayed unless you use the file manager directly.
But this is a guess because your debug log file was not included.
